### ISSUE TITLE
Version 1.9 gateway errors

### ISSUE THREAD

**Issue by StevenBoelhouwer** [gieljnssns/buienalarm-sensor-homeassistant#26] opened 2021-10-03 09:26 UTC
**Describe the bug**
Since a couple of days a gateway error is shown

Error in log:
'Error fetching data safely: HTTPSConnectionPool(host='cdn-secure.buienalarm.nl', port=443): Read timed out. (read timeout=10.0)'

**Comment by gieljnssns** [comment] 2021-10-04 09:26
Duplicate of https://github.com/gieljnssns/buienalarm-sensor-homeassistant/issues/27

**Closed as completed by gieljnssns** 2021-10-04 09:26 UTC
